### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by NataliaPetukhova** [NataliaPetukhova/NataliaPetukhova#3]

**Comment by YakutovDmitriy** [comment]
You've commited file with text from interactive python. You should remove all redundant text (all except for functions): `>>>`, python description, function callings, etc

Here is an example of good executable file:

```
#Problem1
def unique(e):
    return sorted([el for el in set(e)])
```

You can execute this file:
* `python HW1.py`

You can use it from interactive python:
```
$ python
>>> from HW1 import unique
>>> unique([1, 2, 1, 3])
[1, 2, 3]
```

Also I recommend you to refresh in memory information from [the first lecture](https://drive.google.com/drive/folders/1zXC702CPLJe_PXfXb410gzBA36W-8CO2)

**Comment by YakutovDmitriy** [comment]
There is no need to create a new issue after every fix. Task 1 is ok
